//
//  FRPathSearch.h
//  ontherun
//
//  Created by Matt Donahoe on 2/1/11.
//  Copyright 2011 MIT Media Lab. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "FRMap.h"
#import "FRPath.h"

//this object is about storing the shortest paths over a graph. it is generated by the FRMap class.
@interface FRPathSearch : NSObject {
	NSDictionary * previous;
	NSDictionary * distance;
	FRMap * map;
	EdgePos root;
}
- (id) initWithRoot:(EdgePos)r previous:(NSDictionary *)p distance:(NSDictionary *)d map:(FRMap *)m;
- (EdgePos) move:(EdgePos)ep towardRootWithDelta:(float)dx;
- (EdgePos) move:(EdgePos)ep awayFromRootWithDelta:(float)dx;
- (BOOL) isFacingRoot:(EdgePos)ep;
- (BOOL) containsPoint:(EdgePos)ep;
- (float) distanceFromRoot:(EdgePos)ep;
- (NSString *) directionFromRoot:(EdgePos)ep;
@end
